a="""adding ../../../../app.yaml
adding ../../../../appengine/LICENSE
adding ../../../../appengine/README
adding ../../../../appengine/VERSION
adding ../../../../appengine/appcfg.py
adding ../../../../appengine/dev_appserver.py
adding ../../../../appengine/google/__init__.py
adding ../../../../appengine/google/appengine/__init__.py
adding ../../../../appengine/google/appengine/api/__init__.py
adding ../../../../appengine/google/appengine/api/api_base_pb.py
adding ../../../../appengine/google/appengine/api/apiproxy_rpc.py
adding ../../../../appengine/google/appengine/api/apiproxy_stub.py
adding ../../../../appengine/google/appengine/api/apiproxy_stub_map.py
adding ../../../../appengine/google/appengine/api/app_logging.py
adding ../../../../appengine/google/appengine/api/appinfo.py
adding ../../../../appengine/google/appengine/api/appinfo_errors.py
adding ../../../../appengine/google/appengine/api/appinfo_includes.py
adding ../../../../appengine/google/appengine/api/blobstore/__init__.py
adding ../../../../appengine/google/appengine/api/blobstore/blobstore.py
adding ../../../../appengine/google/appengine/api/blobstore/blobstore_service_pb.py
adding ../../../../appengine/google/appengine/api/blobstore/blobstore_stub.py
adding ../../../../appengine/google/appengine/api/blobstore/file_blob_storage.py
adding ../../../../appengine/google/appengine/api/capabilities/__init__.py
adding ../../../../appengine/google/appengine/api/capabilities/capability_service_pb.py
adding ../../../../appengine/google/appengine/api/capabilities/capability_stub.py
adding ../../../../appengine/google/appengine/api/channel/__init__.py
adding ../../../../appengine/google/appengine/api/channel/channel.py
adding ../../../../appengine/google/appengine/api/channel/channel_service_pb.py
adding ../../../../appengine/google/appengine/api/channel/channel_service_stub.py
adding ../../../../appengine/google/appengine/api/croninfo.py
adding ../../../../appengine/google/appengine/api/datastore.py
adding ../../../../appengine/google/appengine/api/datastore_admin.py
adding ../../../../appengine/google/appengine/api/datastore_entities.py
adding ../../../../appengine/google/appengine/api/datastore_errors.py
adding ../../../../appengine/google/appengine/api/datastore_file_stub.py
adding ../../../../appengine/google/appengine/api/datastore_types.py
adding ../../../../appengine/google/appengine/api/dosinfo.py
adding ../../../../appengine/google/appengine/api/files/__init__.py
adding ../../../../appengine/google/appengine/api/files/file_service_pb.py
adding ../../../../appengine/google/appengine/api/files/file_service_stub.py
adding ../../../../appengine/google/appengine/api/images/__init__.py
adding ../../../../appengine/google/appengine/api/images/images_not_implemented_stub.py
adding ../../../../appengine/google/appengine/api/images/images_service_pb.py
adding ../../../../appengine/google/appengine/api/images/images_stub.py
adding ../../../../appengine/google/appengine/api/labs/__init__.py
adding ../../../../appengine/google/appengine/api/labs/taskqueue/__init__.py
adding ../../../../appengine/google/appengine/api/lib_config.py
adding ../../../../appengine/google/appengine/api/logservice/__init__.py
adding ../../../../appengine/google/appengine/api/logservice/log_service_pb.py
adding ../../../../appengine/google/appengine/api/logservice/logservice.py
adding ../../../../appengine/google/appengine/api/mail.py
adding ../../../../appengine/google/appengine/api/mail_errors.py
adding ../../../../appengine/google/appengine/api/mail_service_pb.py
adding ../../../../appengine/google/appengine/api/mail_stub.py
adding ../../../../appengine/google/appengine/api/memcache/__init__.py
adding ../../../../appengine/google/appengine/api/memcache/memcache_service_pb.py
adding ../../../../appengine/google/appengine/api/memcache/memcache_stub.py
adding ../../../../appengine/google/appengine/api/namespace_manager/__init__.py
adding ../../../../appengine/google/appengine/api/namespace_manager/namespace_manager.py
adding ../../../../appengine/google/appengine/api/oauth/__init__.py
adding ../../../../appengine/google/appengine/api/oauth/oauth_api.py
adding ../../../../appengine/google/appengine/api/prospective_search/__init__.py
adding ../../../../appengine/google/appengine/api/prospective_search/error_pb.py
adding ../../../../appengine/google/appengine/api/prospective_search/prospective_search.py
adding ../../../../appengine/google/appengine/api/prospective_search/prospective_search_admin.py
adding ../../../../appengine/google/appengine/api/prospective_search/prospective_search_pb.py
adding ../../../../appengine/google/appengine/api/prospective_search/prospective_search_stub.py
adding ../../../../appengine/google/appengine/api/queueinfo.py
adding ../../../../appengine/google/appengine/api/quota.py
adding ../../../../appengine/google/appengine/api/runtime.py
adding ../../../../appengine/google/appengine/api/taskqueue/__init__.py
adding ../../../../appengine/google/appengine/api/taskqueue/taskqueue.py
adding ../../../../appengine/google/appengine/api/taskqueue/taskqueue_service_pb.py
adding ../../../../appengine/google/appengine/api/taskqueue/taskqueue_stub.py
adding ../../../../appengine/google/appengine/api/urlfetch.py
adding ../../../../appengine/google/appengine/api/urlfetch_errors.py
adding ../../../../appengine/google/appengine/api/urlfetch_service_pb.py
adding ../../../../appengine/google/appengine/api/urlfetch_stub.py
adding ../../../../appengine/google/appengine/api/user_service_pb.py
adding ../../../../appengine/google/appengine/api/user_service_stub.py
adding ../../../../appengine/google/appengine/api/users.py
adding ../../../../appengine/google/appengine/api/validation.py
adding ../../../../appengine/google/appengine/api/xmpp/__init__.py
adding ../../../../appengine/google/appengine/api/xmpp/xmpp_service_pb.py
adding ../../../../appengine/google/appengine/api/xmpp/xmpp_service_stub.py
adding ../../../../appengine/google/appengine/api/yaml_builder.py
adding ../../../../appengine/google/appengine/api/yaml_errors.py
adding ../../../../appengine/google/appengine/api/yaml_listener.py
adding ../../../../appengine/google/appengine/api/yaml_object.py
adding ../../../../appengine/google/appengine/base/__init__.py
adding ../../../../appengine/google/appengine/base/capabilities_pb.py
adding ../../../../appengine/google/appengine/cron/GrocLexer.py
adding ../../../../appengine/google/appengine/cron/GrocParser.py
adding ../../../../appengine/google/appengine/cron/__init__.py
adding ../../../../appengine/google/appengine/cron/groc.py
adding ../../../../appengine/google/appengine/cron/groctimespecification.py
adding ../../../../appengine/google/appengine/datastore/__init__.py
adding ../../../../appengine/google/appengine/datastore/action_pb.py
adding ../../../../appengine/google/appengine/datastore/datastore_index.py
adding ../../../../appengine/google/appengine/datastore/datastore_pb.py
adding ../../../../appengine/google/appengine/datastore/datastore_query.py
adding ../../../../appengine/google/appengine/datastore/datastore_rpc.py
adding ../../../../appengine/google/appengine/datastore/datastore_sqlite_stub.py
adding ../../../../appengine/google/appengine/datastore/datastore_stub_util.py
adding ../../../../appengine/google/appengine/datastore/datastore_v3_pb.py
adding ../../../../appengine/google/appengine/datastore/entity_pb.py
adding ../../../../appengine/google/appengine/datastore/sortable_pb_encoder.py
adding ../../../../appengine/google/appengine/ext/__init__.py
adding ../../../../appengine/google/appengine/ext/admin/__init__.py
adding ../../../../appengine/google/appengine/ext/admin/templates/base.html
adding ../../../../appengine/google/appengine/ext/admin/templates/cron.html
adding ../../../../appengine/google/appengine/ext/admin/templates/css/ae.css
adding ../../../../appengine/google/appengine/ext/admin/templates/css/base.css
adding ../../../../appengine/google/appengine/ext/admin/templates/css/cron.css
adding ../../../../appengine/google/appengine/ext/admin/templates/css/datastore.css
adding ../../../../appengine/google/appengine/ext/admin/templates/css/form.css
adding ../../../../appengine/google/appengine/ext/admin/templates/css/inboundmail.css
adding ../../../../appengine/google/appengine/ext/admin/templates/css/memcache.css
adding ../../../../appengine/google/appengine/ext/admin/templates/css/nav.css
adding ../../../../appengine/google/appengine/ext/admin/templates/css/pager.css
adding ../../../../appengine/google/appengine/ext/admin/templates/css/queues.css
adding ../../../../appengine/google/appengine/ext/admin/templates/css/tasks.css
adding ../../../../appengine/google/appengine/ext/admin/templates/css/xmpp.css
adding ../../../../appengine/google/appengine/ext/admin/templates/datastore.html
adding ../../../../appengine/google/appengine/ext/admin/templates/datastore_edit.html
adding ../../../../appengine/google/appengine/ext/admin/templates/images/google.gif
adding ../../../../appengine/google/appengine/ext/admin/templates/inboundmail.html
adding ../../../../appengine/google/appengine/ext/admin/templates/interactive-output.html
adding ../../../../appengine/google/appengine/ext/admin/templates/interactive.html
adding ../../../../appengine/google/appengine/ext/admin/templates/js/multipart_form_data.js
adding ../../../../appengine/google/appengine/ext/admin/templates/js/rfc822_date.js
adding ../../../../appengine/google/appengine/ext/admin/templates/js/webhook.js
adding ../../../../appengine/google/appengine/ext/admin/templates/memcache.html
adding ../../../../appengine/google/appengine/ext/admin/templates/pager.html
adding ../../../../appengine/google/appengine/ext/admin/templates/queues.html
adding ../../../../appengine/google/appengine/ext/admin/templates/tasks.html
adding ../../../../appengine/google/appengine/ext/admin/templates/xmpp.html
adding ../../../../appengine/google/appengine/ext/admin_redirect/__init__.py
adding ../../../../appengine/google/appengine/ext/admin_redirect/main.py
adding ../../../../appengine/google/appengine/ext/appstats/__init__.py
adding ../../../../appengine/google/appengine/ext/appstats/datamodel_pb.py
adding ../../../../appengine/google/appengine/ext/appstats/formatting.py
adding ../../../../appengine/google/appengine/ext/appstats/recording.py
adding ../../../../appengine/google/appengine/ext/appstats/sample_appengine_config.py
adding ../../../../appengine/google/appengine/ext/appstats/static/app_engine_logo_sm.gif
adding ../../../../appengine/google/appengine/ext/appstats/static/appstats_css.css
adding ../../../../appengine/google/appengine/ext/appstats/static/appstats_js.js
adding ../../../../appengine/google/appengine/ext/appstats/static/gantt.js
adding ../../../../appengine/google/appengine/ext/appstats/static/minus.gif
adding ../../../../appengine/google/appengine/ext/appstats/static/pix.gif
adding ../../../../appengine/google/appengine/ext/appstats/static/plus.gif
adding ../../../../appengine/google/appengine/ext/appstats/templates/base.html
adding ../../../../appengine/google/appengine/ext/appstats/templates/details.html
adding ../../../../appengine/google/appengine/ext/appstats/templates/file.html
adding ../../../../appengine/google/appengine/ext/appstats/templates/main.html
adding ../../../../appengine/google/appengine/ext/appstats/templates/test.html
adding ../../../../appengine/google/appengine/ext/appstats/ui.py
adding ../../../../appengine/google/appengine/ext/blobstore/__init__.py
adding ../../../../appengine/google/appengine/ext/blobstore/blobstore.py
adding ../../../../appengine/google/appengine/ext/builtins/__init__.py
adding ../../../../appengine/google/appengine/ext/builtins/admin_redirect/include.yaml
adding ../../../../appengine/google/appengine/ext/builtins/appstats/include.yaml
adding ../../../../appengine/google/appengine/ext/builtins/datastore_admin/include.yaml
adding ../../../../appengine/google/appengine/ext/builtins/default/include.yaml
adding ../../../../appengine/google/appengine/ext/builtins/deferred/include.yaml
adding ../../../../appengine/google/appengine/ext/builtins/mapreduce/include.yaml
adding ../../../../appengine/google/appengine/ext/builtins/remote_api/include.yaml
adding ../../../../appengine/google/appengine/ext/bulkload/__init__.py
adding ../../../../appengine/google/appengine/ext/bulkload/bulkload_deprecated.py
adding ../../../../appengine/google/appengine/ext/bulkload/bulkloader_config.py
adding ../../../../appengine/google/appengine/ext/bulkload/bulkloader_errors.py
adding ../../../../appengine/google/appengine/ext/bulkload/bulkloader_parser.py
adding ../../../../appengine/google/appengine/ext/bulkload/bulkloader_wizard.py
adding ../../../../appengine/google/appengine/ext/bulkload/bulkloader_wizard.yaml
adding ../../../../appengine/google/appengine/ext/bulkload/connector_interface.py
adding ../../../../appengine/google/appengine/ext/bulkload/constants.py
adding ../../../../appengine/google/appengine/ext/bulkload/csv_connector.py
adding ../../../../appengine/google/appengine/ext/bulkload/simpletext_connector.py
adding ../../../../appengine/google/appengine/ext/bulkload/simplexml_connector.py
adding ../../../../appengine/google/appengine/ext/bulkload/transform.py
adding ../../../../appengine/google/appengine/ext/datastore_admin/__init__.py
adding ../../../../appengine/google/appengine/ext/datastore_admin/copy_handler.py
adding ../../../../appengine/google/appengine/ext/datastore_admin/delete_handler.py
adding ../../../../appengine/google/appengine/ext/datastore_admin/main.py
adding ../../../../appengine/google/appengine/ext/datastore_admin/remote_api_put_stub.py
adding ../../../../appengine/google/appengine/ext/datastore_admin/static/css/compiled.css
adding ../../../../appengine/google/appengine/ext/datastore_admin/static/img/help.gif
adding ../../../../appengine/google/appengine/ext/datastore_admin/static/img/icn/icn-warning.gif
adding ../../../../appengine/google/appengine/ext/datastore_admin/static/img/tip.png
adding ../../../../appengine/google/appengine/ext/datastore_admin/static/js/compiled.js
adding ../../../../appengine/google/appengine/ext/datastore_admin/templates/base.html
adding ../../../../appengine/google/appengine/ext/datastore_admin/templates/confirm_copy.html
adding ../../../../appengine/google/appengine/ext/datastore_admin/templates/confirm_delete.html
adding ../../../../appengine/google/appengine/ext/datastore_admin/templates/do_copy.html
adding ../../../../appengine/google/appengine/ext/datastore_admin/templates/do_delete.html
adding ../../../../appengine/google/appengine/ext/datastore_admin/templates/list_actions.html
adding ../../../../appengine/google/appengine/ext/datastore_admin/utils.py
adding ../../../../appengine/google/appengine/ext/db/__init__.py
adding ../../../../appengine/google/appengine/ext/db/djangoforms.py
adding ../../../../appengine/google/appengine/ext/db/metadata.py
adding ../../../../appengine/google/appengine/ext/db/polymodel.py
adding ../../../../appengine/google/appengine/ext/db/stats.py
adding ../../../../appengine/google/appengine/ext/deferred/__init__.py
adding ../../../../appengine/google/appengine/ext/deferred/deferred.py
adding ../../../../appengine/google/appengine/ext/deferred/handler.py
adding ../../../../appengine/google/appengine/ext/ereporter/__init__.py
adding ../../../../appengine/google/appengine/ext/ereporter/ereporter.py
adding ../../../../appengine/google/appengine/ext/ereporter/report_generator.py
adding ../../../../appengine/google/appengine/ext/ereporter/templates/report.html
adding ../../../../appengine/google/appengine/ext/gql/__init__.py
adding ../../../../appengine/google/appengine/ext/key_range/__init__.py
adding ../../../../appengine/google/appengine/ext/mapreduce/__init__.py
adding ../../../../appengine/google/appengine/ext/mapreduce/base_handler.py
adding ../../../../appengine/google/appengine/ext/mapreduce/context.py
adding ../../../../appengine/google/appengine/ext/mapreduce/control.py
adding ../../../../appengine/google/appengine/ext/mapreduce/handlers.py
adding ../../../../appengine/google/appengine/ext/mapreduce/hooks.py
adding ../../../../appengine/google/appengine/ext/mapreduce/input_readers.py
adding ../../../../appengine/google/appengine/ext/mapreduce/main.py
adding ../../../../appengine/google/appengine/ext/mapreduce/model.py
adding ../../../../appengine/google/appengine/ext/mapreduce/namespace_range.py
adding ../../../../appengine/google/appengine/ext/mapreduce/operation/__init__.py
adding ../../../../appengine/google/appengine/ext/mapreduce/operation/counters.py
adding ../../../../appengine/google/appengine/ext/mapreduce/operation/db.py
adding ../../../../appengine/google/appengine/ext/mapreduce/quota.py
adding ../../../../appengine/google/appengine/ext/mapreduce/static/base.css
adding ../../../../appengine/google/appengine/ext/mapreduce/static/detail.html
adding ../../../../appengine/google/appengine/ext/mapreduce/static/jquery-1.4.2.min.js
adding ../../../../appengine/google/appengine/ext/mapreduce/static/overview.html
adding ../../../../appengine/google/appengine/ext/mapreduce/static/status.js
adding ../../../../appengine/google/appengine/ext/mapreduce/status.py
adding ../../../../appengine/google/appengine/ext/mapreduce/util.py
adding ../../../../appengine/google/appengine/ext/preload/__init__.py
adding ../../../../appengine/google/appengine/ext/remote_api/__init__.py
adding ../../../../appengine/google/appengine/ext/remote_api/handler.py
adding ../../../../appengine/google/appengine/ext/remote_api/remote_api_pb.py
adding ../../../../appengine/google/appengine/ext/remote_api/remote_api_services.py
adding ../../../../appengine/google/appengine/ext/remote_api/remote_api_stub.py
adding ../../../../appengine/google/appengine/ext/remote_api/throttle.py
adding ../../../../appengine/google/appengine/ext/search/__init__.py
adding ../../../../appengine/google/appengine/ext/webapp/__init__.py
adding ../../../../appengine/google/appengine/ext/webapp/blobstore_handlers.py
adding ../../../../appengine/google/appengine/ext/webapp/mail_handlers.py
adding ../../../../appengine/google/appengine/ext/webapp/template.py
adding ../../../../appengine/google/appengine/ext/webapp/util.py
adding ../../../../appengine/google/appengine/ext/webapp/xmpp_handlers.py
adding ../../../../appengine/google/appengine/ext/zipserve/__init__.py
adding ../../../../appengine/google/appengine/runtime/__init__.py
adding ../../../../appengine/google/appengine/runtime/apiproxy.py
adding ../../../../appengine/google/appengine/runtime/apiproxy_errors.py
adding ../../../../appengine/google/appengine/tools/__init__.py
adding ../../../../appengine/google/appengine/tools/adaptive_thread_pool.py
adding ../../../../appengine/google/appengine/tools/appcfg.py
adding ../../../../appengine/google/appengine/tools/appengine_rpc.py
adding ../../../../appengine/google/appengine/tools/bulkload_client.py
adding ../../../../appengine/google/appengine/tools/bulkloader.py
adding ../../../../appengine/google/appengine/tools/dev-channel-js.js
adding ../../../../appengine/google/appengine/tools/dev_appserver.py
adding ../../../../appengine/google/appengine/tools/dev_appserver_blobimage.py
adding ../../../../appengine/google/appengine/tools/dev_appserver_blobstore.py
adding ../../../../appengine/google/appengine/tools/dev_appserver_channel.py
adding ../../../../appengine/google/appengine/tools/dev_appserver_index.py
adding ../../../../appengine/google/appengine/tools/dev_appserver_login.py
adding ../../../../appengine/google/appengine/tools/dev_appserver_main.py
adding ../../../../appengine/google/appengine/tools/dev_appserver_oauth.py
adding ../../../../appengine/google/appengine/tools/dev_appserver_upload.py
adding ../../../../appengine/google/appengine/tools/os_compat.py
adding ../../../../appengine/google/appengine/tools/remote_api_shell.py
adding ../../../../appengine/google/appengine/tools/requeue.py
adding ../../../../appengine/google/net/__init__.py
adding ../../../../appengine/google/net/proto/ProtocolBuffer.py
adding ../../../../appengine/google/net/proto/RawMessage.py
adding ../../../../appengine/google/net/proto/__init__.py
adding ../../../../appengine/google/net/proto/message_set.py
adding ../../../../appengine/google/net/proto2/__init__.py
adding ../../../../appengine/google/net/proto2/proto/__init__.py
adding ../../../../appengine/google/net/proto2/proto/descriptor_pb2.py
adding ../../../../appengine/google/net/proto2/python/__init__.py
adding ../../../../appengine/google/net/proto2/python/internal/__init__.py
adding ../../../../appengine/google/net/proto2/python/internal/api_implementation.py
adding ../../../../appengine/google/net/proto2/python/internal/containers.py
adding ../../../../appengine/google/net/proto2/python/internal/decoder.py
adding ../../../../appengine/google/net/proto2/python/internal/encoder.py
adding ../../../../appengine/google/net/proto2/python/internal/message_listener.py
adding ../../../../appengine/google/net/proto2/python/internal/python_message.py
adding ../../../../appengine/google/net/proto2/python/internal/type_checkers.py
adding ../../../../appengine/google/net/proto2/python/internal/wire_format.py
adding ../../../../appengine/google/net/proto2/python/public/__init__.py
adding ../../../../appengine/google/net/proto2/python/public/descriptor.py
adding ../../../../appengine/google/net/proto2/python/public/message.py
adding ../../../../appengine/google/net/proto2/python/public/reflection.py
adding ../../../../appengine/google/net/proto2/python/public/service.py
adding ../../../../appengine/google/net/proto2/python/public/service_reflection.py
adding ../../../../appengine/google/net/proto2/python/public/text_format.py
adding ../../../../appengine/google/pyglib/__init__.py
adding ../../../../appengine/google/pyglib/gexcept.py
adding ../../../../appengine/lib/antlr3/AUTHORS
adding ../../../../appengine/lib/antlr3/LICENSE
adding ../../../../appengine/lib/antlr3/MANIFEST.in
adding ../../../../appengine/lib/antlr3/OWNERS
adding ../../../../appengine/lib/antlr3/README
adding ../../../../appengine/lib/antlr3/antlr3/__init__.py
adding ../../../../appengine/lib/antlr3/antlr3/compat.py
adding ../../../../appengine/lib/antlr3/antlr3/constants.py
adding ../../../../appengine/lib/antlr3/antlr3/dfa.py
adding ../../../../appengine/lib/antlr3/antlr3/dottreegen.py
adding ../../../../appengine/lib/antlr3/antlr3/exceptions.py
adding ../../../../appengine/lib/antlr3/antlr3/extras.py
adding ../../../../appengine/lib/antlr3/antlr3/main.py
adding ../../../../appengine/lib/antlr3/antlr3/recognizers.py
adding ../../../../appengine/lib/antlr3/antlr3/streams.py
adding ../../../../appengine/lib/antlr3/antlr3/tokens.py
adding ../../../../appengine/lib/antlr3/antlr3/tree.py
adding ../../../../appengine/lib/antlr3/antlr3/treewizard.py
adding ../../../../appengine/lib/antlr3/antlr_python_runtime.egg-info/PKG-INFO
adding ../../../../appengine/lib/antlr3/antlr_python_runtime.egg-info/SOURCES.txt
adding ../../../../appengine/lib/antlr3/antlr_python_runtime.egg-info/dependency_links.txt
adding ../../../../appengine/lib/antlr3/antlr_python_runtime.egg-info/top_level.txt
adding ../../../../appengine/lib/antlr3/setup.py
adding ../../../../appengine/lib/cacerts/cacerts.txt
adding ../../../../appengine/lib/cacerts/urlfetch_cacerts.txt
adding ../../../../appengine/lib/fancy_urllib/__init__.py
adding ../../../../appengine/lib/fancy_urllib/fancy_urllib/__init__.py
adding ../../../../appengine/lib/ipaddr/ipaddr/COPYING
adding ../../../../appengine/lib/ipaddr/ipaddr/README
adding ../../../../appengine/lib/ipaddr/ipaddr/__init__.py
adding ../../../../appengine/lib/ipaddr/ipaddr/ipaddr_test.py
adding ../../../../appengine/lib/ipaddr/ipaddr/setup.py
adding ../../../../appengine/lib/yaml/LICENSE
adding ../../../../appengine/lib/yaml/PKG-INFO
adding ../../../../appengine/lib/yaml/README
adding ../../../../appengine/lib/yaml/examples/yaml-highlight/yaml_hl.cfg
adding ../../../../appengine/lib/yaml/examples/yaml-highlight/yaml_hl.py
adding ../../../../appengine/lib/yaml/lib/yaml/__init__.py
adding ../../../../appengine/lib/yaml/lib/yaml/composer.py
adding ../../../../appengine/lib/yaml/lib/yaml/constructor.py
adding ../../../../appengine/lib/yaml/lib/yaml/cyaml.py
adding ../../../../appengine/lib/yaml/lib/yaml/dumper.py
adding ../../../../appengine/lib/yaml/lib/yaml/emitter.py
adding ../../../../appengine/lib/yaml/lib/yaml/error.py
adding ../../../../appengine/lib/yaml/lib/yaml/events.py
adding ../../../../appengine/lib/yaml/lib/yaml/loader.py
adding ../../../../appengine/lib/yaml/lib/yaml/nodes.py
adding ../../../../appengine/lib/yaml/lib/yaml/parser.py
adding ../../../../appengine/lib/yaml/lib/yaml/reader.py
adding ../../../../appengine/lib/yaml/lib/yaml/representer.py
adding ../../../../appengine/lib/yaml/lib/yaml/resolver.py
adding ../../../../appengine/lib/yaml/lib/yaml/scanner.py
adding ../../../../appengine/lib/yaml/lib/yaml/serializer.py
adding ../../../../appengine/lib/yaml/lib/yaml/tokens.py
adding ../../../../appengine/lib/yaml/setup.cfg
adding ../../../../appengine/lib/yaml/setup.py
adding ../../../../appengine/lib/yaml/setup_with_libyaml.py
adding ../../../../appengine/templates/logging_console.js
adding ../../../../appengine/templates/logging_console_footer.html
adding ../../../../appengine/templates/logging_console_header.html
adding ../../../../appengine/templates/logging_console_middle.html
adding ../../../admin/private/hosts.deny
adding ../../../admin/static/codemirror/LICENSE
adding ../../../admin/static/codemirror/README.md
adding ../../../admin/static/codemirror/compress.html
adding ../../../admin/static/codemirror/css/baboon.png
adding ../../../admin/static/codemirror/css/baboon_vector.svg
adding ../../../admin/static/codemirror/css/docs.css
adding ../../../admin/static/codemirror/css/font.js
adding ../../../admin/static/codemirror/demo/activeline.html
adding ../../../admin/static/codemirror/demo/complete.html
adding ../../../admin/static/codemirror/demo/complete.js
adding ../../../admin/static/codemirror/demo/marker.html
adding ../../../admin/static/codemirror/demo/mustache.html
adding ../../../admin/static/codemirror/demo/resize.html
adding ../../../admin/static/codemirror/demo/search.html
adding ../../../admin/static/codemirror/index.html
adding ../../../admin/static/codemirror/internals.html
adding ../../../admin/static/codemirror/lib/codemirror.css
adding ../../../admin/static/codemirror/lib/codemirror.js
adding ../../../admin/static/codemirror/lib/overlay.js
adding ../../../admin/static/codemirror/manual.html
adding ../../../admin/static/codemirror/mode/clike/clike.css
adding ../../../admin/static/codemirror/mode/clike/clike.js
adding ../../../admin/static/codemirror/mode/clike/index.html
adding ../../../admin/static/codemirror/mode/css/css.css
adding ../../../admin/static/codemirror/mode/css/css.js
adding ../../../admin/static/codemirror/mode/css/index.html
adding ../../../admin/static/codemirror/mode/diff/diff.css
adding ../../../admin/static/codemirror/mode/diff/diff.js
adding ../../../admin/static/codemirror/mode/diff/index.html
adding ../../../admin/static/codemirror/mode/haskell/haskell.css
adding ../../../admin/static/codemirror/mode/haskell/haskell.js
adding ../../../admin/static/codemirror/mode/haskell/index.html
adding ../../../admin/static/codemirror/mode/htmlmixed/htmlmixed.js
adding ../../../admin/static/codemirror/mode/htmlmixed/index.html
adding ../../../admin/static/codemirror/mode/javascript/index.html
adding ../../../admin/static/codemirror/mode/javascript/javascript.css
adding ../../../admin/static/codemirror/mode/javascript/javascript.js
adding ../../../admin/static/codemirror/mode/php/index.html
adding ../../../admin/static/codemirror/mode/php/php.js
adding ../../../admin/static/codemirror/mode/stex/index.html
adding ../../../admin/static/codemirror/mode/stex/stex.css
adding ../../../admin/static/codemirror/mode/stex/stex.js
adding ../../../admin/static/codemirror/mode/xml/index.html
adding ../../../admin/static/codemirror/mode/xml/xml.css
adding ../../../admin/static/codemirror/mode/xml/xml.js
adding ../../../admin/static/codemirror/oldrelease.html
adding ../../../admin/static/codemirror/test/index.html
adding ../../../admin/static/codemirror/test/test.js
adding ../../../examples.tgz
adding ../../../examples/models/cache_examples/db.py
adding ../../../examples/models/database_examples/db.py
adding ../../../examples/static/css/ie7.css
adding ../../../examples/static/css/style.css
adding ../../../examples/static/images/1-w2p-welcome-thumb.jpg
adding ../../../examples/static/images/2-w2p-login-thumb.jpg
adding ../../../examples/static/images/3-w2p-site-thumb.jpg
adding ../../../examples/static/images/4-w2p-edit-thumb.jpg
adding ../../../examples/static/images/background.png
adding ../../../examples/static/images/cart.png
adding ../../../examples/static/images/glow.png
adding ../../../examples/static/images/search.png
adding ../../../examples/static/images/shadow-bottom.png
adding ../../../examples/static/images/shadow-top.png
adding ../../../examples/static/images/system.png
adding ../../../examples/static/images/tab-active.png
adding ../../../examples/static/images/tablet.png
adding ../../../examples/static/images/tools.png
adding ../../../examples/static/images/web2py_logo.png
adding ../../../examples/static/images/web2py_logo_light.png
adding ../../../examples/static/js/common.js
adding ../../../examples/static/js/dd_belatedpng.js
adding ../../../examples/static/js/jquery-1.5-min.js
adding ../../../examples/static/js/jquery.prettyPhoto.js
adding ../../../examples/static/js/modernizr-1.6.min.js
adding ../../../examples/views/default/index2.html
adding skeleton.css
adding web2py.css
adding ../../../welcome2/ABOUT
adding ../../../welcome2/LICENSE
adding ../../../welcome2/__init__.py
adding ../../../welcome2/controllers/appadmin.py
adding ../../../welcome2/controllers/default.py
adding ../../../welcome2/cron/crontab
adding ../../../welcome2/languages/cs-cz.py
adding ../../../welcome2/languages/es-es.py
adding ../../../welcome2/languages/fr-ca.py
adding ../../../welcome2/languages/fr-fr.py
adding ../../../welcome2/languages/hi-hi.py
adding ../../../welcome2/languages/hu-hu.py
adding ../../../welcome2/languages/hu.py
adding ../../../welcome2/languages/it-it.py
adding ../../../welcome2/languages/it.py
adding ../../../welcome2/languages/pl-pl.py
adding ../../../welcome2/languages/pl.py
adding ../../../welcome2/languages/pt-br.py
adding ../../../welcome2/languages/pt-pt.py
adding ../../../welcome2/languages/pt.py
adding ../../../welcome2/languages/ru-ru.py
adding ../../../welcome2/languages/sk-sk.py
adding ../../../welcome2/languages/zh-tw.py
adding ../../../welcome2/models/db.py
adding ../../../welcome2/models/menu.py
adding ../../../welcome2/modules/__init__.py
adding ../../../welcome2/private/auth.key
adding ../../../welcome2/static/css/anytime.css
adding ../../../welcome2/static/css/base.css
adding ../../../welcome2/static/css/dropdown.css
adding ../../../welcome2/static/css/dropdown/themes/default/default.css
adding ../../../welcome2/static/css/handheld.css
adding ../../../welcome2/static/favicon.ico
adding ../../../welcome2/static/favicon.png
adding ../../../welcome2/static/images/arrows-ffffff.png
adding ../../../welcome2/static/images/css3buttons_backgrounds.png
adding ../../../welcome2/static/images/css3buttons_icons.png
adding ../../../welcome2/static/images/poweredby.png
adding ../../../welcome2/static/images/shadow.png
adding ../../../welcome2/static/images/ui-icons_222222_256x240.png
adding ../../../welcome2/static/js/anytime.js
adding ../../../welcome2/static/js/dd_belatedpng.js
adding ../../../welcome2/static/js/jquery.dropdown.js
adding ../../../welcome2/static/js/jquery.js
adding ../../../welcome2/static/js/modernizr-1.7.min.js
adding ../../../welcome2/static/js/web2py_ajax.js
adding ../../../welcome2/static/robots.txt
adding ../../../welcome2/views/__init__.py
adding ../../../welcome2/views/appadmin.html
adding ../../../welcome2/views/default/index.html
adding ../../../welcome2/views/default/user.html
adding ../../../welcome2/views/generic.html
adding ../../../welcome2/views/generic.json
adding ../../../welcome2/views/generic.jsonp
adding ../../../welcome2/views/generic.load
adding ../../../welcome2/views/generic.pdf
adding ../../../welcome2/views/generic.rss
adding ../../../welcome2/views/generic.xml
adding ../../../welcome2/views/layout.html
adding ../../../welcome2/views/web2py_ajax.html
adding ../../../../archive
adding ../../../../b/gluon/tests/test_storage.py
adding ../../../../count_lines.py
adding ../../../../cron.master
adding ../../../../gluon/contrib/markmin/test.markmin
adding ../../../../gluon/scheduler.py.main
adding ../../../../gluon/scheduler.py.old
adding ../../../../gluon/storage.sqlite
adding ../../../../gluon/storage2.py
adding ../../../../gluon/tools.py.ok
adding ../../../../google_appengine/LICENSE
adding ../../../../google_appengine/README
adding ../../../../google_appengine/VERSION
adding ../../../../google_appengine/appcfg.py
adding ../../../../google_appengine/dev_appserver.py
adding ../../../../google_appengine/google/__init__.py
adding ../../../../google_appengine/google/appengine/__init__.py
adding ../../../../google_appengine/google/appengine/api/__init__.py
adding ../../../../google_appengine/google/appengine/api/api_base_pb.py
adding ../../../../google_appengine/google/appengine/api/apiproxy_rpc.py
adding ../../../../google_appengine/google/appengine/api/apiproxy_stub.py
adding ../../../../google_appengine/google/appengine/api/apiproxy_stub_map.py
adding ../../../../google_appengine/google/appengine/api/app_logging.py
adding ../../../../google_appengine/google/appengine/api/appinfo.py
adding ../../../../google_appengine/google/appengine/api/appinfo_errors.py
adding ../../../../google_appengine/google/appengine/api/appinfo_includes.py
adding ../../../../google_appengine/google/appengine/api/blobstore/__init__.py
adding ../../../../google_appengine/google/appengine/api/blobstore/blobstore.py
adding ../../../../google_appengine/google/appengine/api/blobstore/blobstore_service_pb.py
adding ../../../../google_appengine/google/appengine/api/blobstore/blobstore_stub.py
adding ../../../../google_appengine/google/appengine/api/blobstore/file_blob_storage.py
adding ../../../../google_appengine/google/appengine/api/capabilities/__init__.py
adding ../../../../google_appengine/google/appengine/api/capabilities/capability_service_pb.py
adding ../../../../google_appengine/google/appengine/api/capabilities/capability_stub.py
adding ../../../../google_appengine/google/appengine/api/channel/__init__.py
adding ../../../../google_appengine/google/appengine/api/channel/channel.py
adding ../../../../google_appengine/google/appengine/api/channel/channel_service_pb.py
adding ../../../../google_appengine/google/appengine/api/channel/channel_service_stub.py
adding ../../../../google_appengine/google/appengine/api/croninfo.py
adding ../../../../google_appengine/google/appengine/api/datastore.py
adding ../../../../google_appengine/google/appengine/api/datastore_admin.py
adding ../../../../google_appengine/google/appengine/api/datastore_entities.py
adding ../../../../google_appengine/google/appengine/api/datastore_errors.py
adding ../../../../google_appengine/google/appengine/api/datastore_file_stub.py
adding ../../../../google_appengine/google/appengine/api/datastore_types.py
adding ../../../../google_appengine/google/appengine/api/dosinfo.py
adding ../../../../google_appengine/google/appengine/api/files/__init__.py
adding ../../../../google_appengine/google/appengine/api/files/file_service_pb.py
adding ../../../../google_appengine/google/appengine/api/files/file_service_stub.py
adding ../../../../google_appengine/google/appengine/api/images/__init__.py
adding ../../../../google_appengine/google/appengine/api/images/images_not_implemented_stub.py
adding ../../../../google_appengine/google/appengine/api/images/images_service_pb.py
adding ../../../../google_appengine/google/appengine/api/images/images_stub.py
adding ../../../../google_appengine/google/appengine/api/labs/__init__.py
adding ../../../../google_appengine/google/appengine/api/labs/taskqueue/__init__.py
adding ../../../../google_appengine/google/appengine/api/lib_config.py
adding ../../../../google_appengine/google/appengine/api/logservice/__init__.py
adding ../../../../google_appengine/google/appengine/api/logservice/log_service_pb.py
adding ../../../../google_appengine/google/appengine/api/logservice/logservice.py
adding ../../../../google_appengine/google/appengine/api/mail.py
adding ../../../../google_appengine/google/appengine/api/mail_errors.py
adding ../../../../google_appengine/google/appengine/api/mail_service_pb.py
adding ../../../../google_appengine/google/appengine/api/mail_stub.py
adding ../../../../google_appengine/google/appengine/api/memcache/__init__.py
adding ../../../../google_appengine/google/appengine/api/memcache/memcache_service_pb.py
adding ../../../../google_appengine/google/appengine/api/memcache/memcache_stub.py
adding ../../../../google_appengine/google/appengine/api/namespace_manager/__init__.py
adding ../../../../google_appengine/google/appengine/api/namespace_manager/namespace_manager.py
adding ../../../../google_appengine/google/appengine/api/oauth/__init__.py
adding ../../../../google_appengine/google/appengine/api/oauth/oauth_api.py
adding ../../../../google_appengine/google/appengine/api/prospective_search/__init__.py
adding ../../../../google_appengine/google/appengine/api/prospective_search/error_pb.py
adding ../../../../google_appengine/google/appengine/api/prospective_search/prospective_search.py
adding ../../../../google_appengine/google/appengine/api/prospective_search/prospective_search_admin.py
adding ../../../../google_appengine/google/appengine/api/prospective_search/prospective_search_pb.py
adding ../../../../google_appengine/google/appengine/api/prospective_search/prospective_search_stub.py
adding ../../../../google_appengine/google/appengine/api/queueinfo.py
adding ../../../../google_appengine/google/appengine/api/quota.py
adding ../../../../google_appengine/google/appengine/api/runtime.py
adding ../../../../google_appengine/google/appengine/api/taskqueue/__init__.py
adding ../../../../google_appengine/google/appengine/api/taskqueue/taskqueue.py
adding ../../../../google_appengine/google/appengine/api/taskqueue/taskqueue_service_pb.py
adding ../../../../google_appengine/google/appengine/api/taskqueue/taskqueue_stub.py
adding ../../../../google_appengine/google/appengine/api/urlfetch.py
adding ../../../../google_appengine/google/appengine/api/urlfetch_errors.py
adding ../../../../google_appengine/google/appengine/api/urlfetch_service_pb.py
adding ../../../../google_appengine/google/appengine/api/urlfetch_stub.py
adding ../../../../google_appengine/google/appengine/api/user_service_pb.py
adding ../../../../google_appengine/google/appengine/api/user_service_stub.py
adding ../../../../google_appengine/google/appengine/api/users.py
adding ../../../../google_appengine/google/appengine/api/validation.py
adding ../../../../google_appengine/google/appengine/api/xmpp/__init__.py
adding ../../../../google_appengine/google/appengine/api/xmpp/xmpp_service_pb.py
adding ../../../../google_appengine/google/appengine/api/xmpp/xmpp_service_stub.py
adding ../../../../google_appengine/google/appengine/api/yaml_builder.py
adding ../../../../google_appengine/google/appengine/api/yaml_errors.py
adding ../../../../google_appengine/google/appengine/api/yaml_listener.py
adding ../../../../google_appengine/google/appengine/api/yaml_object.py
adding ../../../../google_appengine/google/appengine/base/__init__.py
adding ../../../../google_appengine/google/appengine/base/capabilities_pb.py
adding ../../../../google_appengine/google/appengine/cron/GrocLexer.py
adding ../../../../google_appengine/google/appengine/cron/GrocParser.py
adding ../../../../google_appengine/google/appengine/cron/__init__.py
adding ../../../../google_appengine/google/appengine/cron/groc.py
adding ../../../../google_appengine/google/appengine/cron/groctimespecification.py
adding ../../../../google_appengine/google/appengine/datastore/__init__.py
adding ../../../../google_appengine/google/appengine/datastore/action_pb.py
adding ../../../../google_appengine/google/appengine/datastore/datastore_index.py
adding ../../../../google_appengine/google/appengine/datastore/datastore_pb.py
adding ../../../../google_appengine/google/appengine/datastore/datastore_query.py
adding ../../../../google_appengine/google/appengine/datastore/datastore_rpc.py
adding ../../../../google_appengine/google/appengine/datastore/datastore_sqlite_stub.py
adding ../../../../google_appengine/google/appengine/datastore/datastore_stub_util.py
adding ../../../../google_appengine/google/appengine/datastore/datastore_v3_pb.py
adding ../../../../google_appengine/google/appengine/datastore/entity_pb.py
adding ../../../../google_appengine/google/appengine/datastore/sortable_pb_encoder.py
adding ../../../../google_appengine/google/appengine/ext/__init__.py
adding ../../../../google_appengine/google/appengine/ext/admin/__init__.py
adding ../../../../google_appengine/google/appengine/ext/admin/templates/base.html
adding ../../../../google_appengine/google/appengine/ext/admin/templates/cron.html
adding ../../../../google_appengine/google/appengine/ext/admin/templates/css/ae.css
adding ../../../../google_appengine/google/appengine/ext/admin/templates/css/base.css
adding ../../../../google_appengine/google/appengine/ext/admin/templates/css/cron.css
adding ../../../../google_appengine/google/appengine/ext/admin/templates/css/datastore.css
adding ../../../../google_appengine/google/appengine/ext/admin/templates/css/form.css
adding ../../../../google_appengine/google/appengine/ext/admin/templates/css/inboundmail.css
adding ../../../../google_appengine/google/appengine/ext/admin/templates/css/memcache.css
adding ../../../../google_appengine/google/appengine/ext/admin/templates/css/nav.css
adding ../../../../google_appengine/google/appengine/ext/admin/templates/css/pager.css
adding ../../../../google_appengine/google/appengine/ext/admin/templates/css/queues.css
adding ../../../../google_appengine/google/appengine/ext/admin/templates/css/tasks.css
adding ../../../../google_appengine/google/appengine/ext/admin/templates/css/xmpp.css
adding ../../../../google_appengine/google/appengine/ext/admin/templates/datastore.html
adding ../../../../google_appengine/google/appengine/ext/admin/templates/datastore_edit.html
adding ../../../../google_appengine/google/appengine/ext/admin/templates/images/google.gif
adding ../../../../google_appengine/google/appengine/ext/admin/templates/inboundmail.html
adding ../../../../google_appengine/google/appengine/ext/admin/templates/interactive-output.html
adding ../../../../google_appengine/google/appengine/ext/admin/templates/interactive.html
adding ../../../../google_appengine/google/appengine/ext/admin/templates/js/multipart_form_data.js
adding ../../../../google_appengine/google/appengine/ext/admin/templates/js/rfc822_date.js
adding ../../../../google_appengine/google/appengine/ext/admin/templates/js/webhook.js
adding ../../../../google_appengine/google/appengine/ext/admin/templates/memcache.html
adding ../../../../google_appengine/google/appengine/ext/admin/templates/pager.html
adding ../../../../google_appengine/google/appengine/ext/admin/templates/queues.html
adding ../../../../google_appengine/google/appengine/ext/admin/templates/tasks.html
adding ../../../../google_appengine/google/appengine/ext/admin/templates/xmpp.html
adding ../../../../google_appengine/google/appengine/ext/admin_redirect/__init__.py
adding ../../../../google_appengine/google/appengine/ext/admin_redirect/main.py
adding ../../../../google_appengine/google/appengine/ext/appstats/__init__.py
adding ../../../../google_appengine/google/appengine/ext/appstats/datamodel_pb.py
adding ../../../../google_appengine/google/appengine/ext/appstats/formatting.py
adding ../../../../google_appengine/google/appengine/ext/appstats/recording.py
adding ../../../../google_appengine/google/appengine/ext/appstats/sample_appengine_config.py
adding ../../../../google_appengine/google/appengine/ext/appstats/static/app_engine_logo_sm.gif
adding ../../../../google_appengine/google/appengine/ext/appstats/static/appstats_css.css
adding ../../../../google_appengine/google/appengine/ext/appstats/static/appstats_js.js
adding ../../../../google_appengine/google/appengine/ext/appstats/static/gantt.js
adding ../../../../google_appengine/google/appengine/ext/appstats/static/minus.gif
adding ../../../../google_appengine/google/appengine/ext/appstats/static/pix.gif
adding ../../../../google_appengine/google/appengine/ext/appstats/static/plus.gif
adding ../../../../google_appengine/google/appengine/ext/appstats/templates/base.html
adding ../../../../google_appengine/google/appengine/ext/appstats/templates/details.html
adding ../../../../google_appengine/google/appengine/ext/appstats/templates/file.html
adding ../../../../google_appengine/google/appengine/ext/appstats/templates/main.html
adding ../../../../google_appengine/google/appengine/ext/appstats/templates/test.html
adding ../../../../google_appengine/google/appengine/ext/appstats/ui.py
adding ../../../../google_appengine/google/appengine/ext/blobstore/__init__.py
adding ../../../../google_appengine/google/appengine/ext/blobstore/blobstore.py
adding ../../../../google_appengine/google/appengine/ext/builtins/__init__.py
adding ../../../../google_appengine/google/appengine/ext/builtins/admin_redirect/include.yaml
adding ../../../../google_appengine/google/appengine/ext/builtins/appstats/include.yaml
adding ../../../../google_appengine/google/appengine/ext/builtins/datastore_admin/include.yaml
adding ../../../../google_appengine/google/appengine/ext/builtins/default/include.yaml
adding ../../../../google_appengine/google/appengine/ext/builtins/deferred/include.yaml
adding ../../../../google_appengine/google/appengine/ext/builtins/mapreduce/include.yaml
adding ../../../../google_appengine/google/appengine/ext/builtins/remote_api/include.yaml
adding ../../../../google_appengine/google/appengine/ext/bulkload/__init__.py
adding ../../../../google_appengine/google/appengine/ext/bulkload/bulkload_deprecated.py
adding ../../../../google_appengine/google/appengine/ext/bulkload/bulkloader_config.py
adding ../../../../google_appengine/google/appengine/ext/bulkload/bulkloader_errors.py
adding ../../../../google_appengine/google/appengine/ext/bulkload/bulkloader_parser.py
adding ../../../../google_appengine/google/appengine/ext/bulkload/bulkloader_wizard.py
adding ../../../../google_appengine/google/appengine/ext/bulkload/bulkloader_wizard.yaml
adding ../../../../google_appengine/google/appengine/ext/bulkload/connector_interface.py
adding ../../../../google_appengine/google/appengine/ext/bulkload/constants.py
adding ../../../../google_appengine/google/appengine/ext/bulkload/csv_connector.py
adding ../../../../google_appengine/google/appengine/ext/bulkload/simpletext_connector.py
adding ../../../../google_appengine/google/appengine/ext/bulkload/simplexml_connector.py
adding ../../../../google_appengine/google/appengine/ext/bulkload/transform.py
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/__init__.py
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/copy_handler.py
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/delete_handler.py
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/main.py
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/remote_api_put_stub.py
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/static/css/compiled.css
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/static/img/help.gif
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/static/img/icn/icn-warning.gif
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/static/img/tip.png
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/static/js/compiled.js
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/templates/base.html
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/templates/confirm_copy.html
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/templates/confirm_delete.html
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/templates/do_copy.html
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/templates/do_delete.html
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/templates/list_actions.html
adding ../../../../google_appengine/google/appengine/ext/datastore_admin/utils.py
adding ../../../../google_appengine/google/appengine/ext/db/__init__.py
adding ../../../../google_appengine/google/appengine/ext/db/djangoforms.py
adding ../../../../google_appengine/google/appengine/ext/db/metadata.py
adding ../../../../google_appengine/google/appengine/ext/db/polymodel.py
adding ../../../../google_appengine/google/appengine/ext/db/stats.py
adding ../../../../google_appengine/google/appengine/ext/deferred/__init__.py
adding ../../../../google_appengine/google/appengine/ext/deferred/deferred.py
adding ../../../../google_appengine/google/appengine/ext/deferred/handler.py
adding ../../../../google_appengine/google/appengine/ext/ereporter/__init__.py
adding ../../../../google_appengine/google/appengine/ext/ereporter/ereporter.py
adding ../../../../google_appengine/google/appengine/ext/ereporter/report_generator.py
adding ../../../../google_appengine/google/appengine/ext/ereporter/templates/report.html
adding ../../../../google_appengine/google/appengine/ext/gql/__init__.py
adding ../../../../google_appengine/google/appengine/ext/key_range/__init__.py
adding ../../../../google_appengine/google/appengine/ext/mapreduce/__init__.py
adding ../../../../google_appengine/google/appengine/ext/mapreduce/base_handler.py
adding ../../../../google_appengine/google/appengine/ext/mapreduce/context.py
adding ../../../../google_appengine/google/appengine/ext/mapreduce/control.py
adding ../../../../google_appengine/google/appengine/ext/mapreduce/handlers.py
adding ../../../../google_appengine/google/appengine/ext/mapreduce/hooks.py
adding ../../../../google_appengine/google/appengine/ext/mapreduce/input_readers.py
adding ../../../../google_appengine/google/appengine/ext/mapreduce/main.py
adding ../../../../google_appengine/google/appengine/ext/mapreduce/model.py
adding ../../../../google_appengine/google/appengine/ext/mapreduce/namespace_range.py
adding ../../../../google_appengine/google/appengine/ext/mapreduce/operation/__init__.py
adding ../../../../google_appengine/google/appengine/ext/mapreduce/operation/counters.py
adding ../../../../google_appengine/google/appengine/ext/mapreduce/operation/db.py
adding ../../../../google_appengine/google/appengine/ext/mapreduce/quota.py
adding ../../../../google_appengine/google/appengine/ext/mapreduce/static/base.css
adding ../../../../google_appengine/google/appengine/ext/mapreduce/static/detail.html
adding ../../../../google_appengine/google/appengine/ext/mapreduce/static/jquery-1.4.2.min.js
adding ../../../../google_appengine/google/appengine/ext/mapreduce/static/overview.html
adding ../../../../google_appengine/google/appengine/ext/mapreduce/static/status.js
adding ../../../../google_appengine/google/appengine/ext/mapreduce/status.py
adding ../../../../google_appengine/google/appengine/ext/mapreduce/util.py
adding ../../../../google_appengine/google/appengine/ext/preload/__init__.py
adding ../../../../google_appengine/google/appengine/ext/remote_api/__init__.py
adding ../../../../google_appengine/google/appengine/ext/remote_api/handler.py
adding ../../../../google_appengine/google/appengine/ext/remote_api/remote_api_pb.py
adding ../../../../google_appengine/google/appengine/ext/remote_api/remote_api_services.py
adding ../../../../google_appengine/google/appengine/ext/remote_api/remote_api_stub.py
adding ../../../../google_appengine/google/appengine/ext/remote_api/throttle.py
adding ../../../../google_appengine/google/appengine/ext/search/__init__.py
adding ../../../../google_appengine/google/appengine/ext/webapp/__init__.py
adding ../../../../google_appengine/google/appengine/ext/webapp/blobstore_handlers.py
adding ../../../../google_appengine/google/appengine/ext/webapp/mail_handlers.py
adding ../../../../google_appengine/google/appengine/ext/webapp/template.py
adding ../../../../google_appengine/google/appengine/ext/webapp/util.py
adding ../../../../google_appengine/google/appengine/ext/webapp/xmpp_handlers.py
adding ../../../../google_appengine/google/appengine/ext/zipserve/__init__.py
adding ../../../../google_appengine/google/appengine/runtime/__init__.py
adding ../../../../google_appengine/google/appengine/runtime/apiproxy.py
adding ../../../../google_appengine/google/appengine/runtime/apiproxy_errors.py
adding ../../../../google_appengine/google/appengine/tools/__init__.py
adding ../../../../google_appengine/google/appengine/tools/adaptive_thread_pool.py
adding ../../../../google_appengine/google/appengine/tools/appcfg.py
adding ../../../../google_appengine/google/appengine/tools/appengine_rpc.py
adding ../../../../google_appengine/google/appengine/tools/bulkload_client.py
adding ../../../../google_appengine/google/appengine/tools/bulkloader.py
adding ../../../../google_appengine/google/appengine/tools/dev-channel-js.js
adding ../../../../google_appengine/google/appengine/tools/dev_appserver.py
adding ../../../../google_appengine/google/appengine/tools/dev_appserver_blobimage.py
adding ../../../../google_appengine/google/appengine/tools/dev_appserver_blobstore.py
adding ../../../../google_appengine/google/appengine/tools/dev_appserver_channel.py
adding ../../../../google_appengine/google/appengine/tools/dev_appserver_index.py
adding ../../../../google_appengine/google/appengine/tools/dev_appserver_login.py
adding ../../../../google_appengine/google/appengine/tools/dev_appserver_main.py
adding ../../../../google_appengine/google/appengine/tools/dev_appserver_oauth.py
adding ../../../../google_appengine/google/appengine/tools/dev_appserver_upload.py
adding ../../../../google_appengine/google/appengine/tools/os_compat.py
adding ../../../../google_appengine/google/appengine/tools/remote_api_shell.py
adding ../../../../google_appengine/google/appengine/tools/requeue.py
adding ../../../../google_appengine/google/net/__init__.py
adding ../../../../google_appengine/google/net/proto/ProtocolBuffer.py
adding ../../../../google_appengine/google/net/proto/RawMessage.py
adding ../../../../google_appengine/google/net/proto/__init__.py
adding ../../../../google_appengine/google/net/proto/message_set.py
adding ../../../../google_appengine/google/net/proto2/__init__.py
adding ../../../../google_appengine/google/net/proto2/proto/__init__.py
adding ../../../../google_appengine/google/net/proto2/proto/descriptor_pb2.py
adding ../../../../google_appengine/google/net/proto2/python/__init__.py
adding ../../../../google_appengine/google/net/proto2/python/internal/__init__.py
adding ../../../../google_appengine/google/net/proto2/python/internal/api_implementation.py
adding ../../../../google_appengine/google/net/proto2/python/internal/containers.py
adding ../../../../google_appengine/google/net/proto2/python/internal/decoder.py
adding ../../../../google_appengine/google/net/proto2/python/internal/encoder.py
adding ../../../../google_appengine/google/net/proto2/python/internal/message_listener.py
adding ../../../../google_appengine/google/net/proto2/python/internal/python_message.py
adding ../../../../google_appengine/google/net/proto2/python/internal/type_checkers.py
adding ../../../../google_appengine/google/net/proto2/python/internal/wire_format.py
adding ../../../../google_appengine/google/net/proto2/python/public/__init__.py
adding ../../../../google_appengine/google/net/proto2/python/public/descriptor.py
adding ../../../../google_appengine/google/net/proto2/python/public/message.py
adding ../../../../google_appengine/google/net/proto2/python/public/reflection.py
adding ../../../../google_appengine/google/net/proto2/python/public/service.py
adding ../../../../google_appengine/google/net/proto2/python/public/service_reflection.py
adding ../../../../google_appengine/google/net/proto2/python/public/text_format.py
adding ../../../../google_appengine/google/pyglib/__init__.py
adding ../../../../google_appengine/google/pyglib/gexcept.py
adding ../../../../google_appengine/lib/antlr3/AUTHORS
adding ../../../../google_appengine/lib/antlr3/LICENSE
adding ../../../../google_appengine/lib/antlr3/MANIFEST.in
adding ../../../../google_appengine/lib/antlr3/OWNERS
adding ../../../../google_appengine/lib/antlr3/README
adding ../../../../google_appengine/lib/antlr3/antlr3/__init__.py
adding ../../../../google_appengine/lib/antlr3/antlr3/compat.py
adding ../../../../google_appengine/lib/antlr3/antlr3/constants.py
adding ../../../../google_appengine/lib/antlr3/antlr3/dfa.py
adding ../../../../google_appengine/lib/antlr3/antlr3/dottreegen.py
adding ../../../../google_appengine/lib/antlr3/antlr3/exceptions.py
adding ../../../../google_appengine/lib/antlr3/antlr3/extras.py
adding ../../../../google_appengine/lib/antlr3/antlr3/main.py
adding ../../../../google_appengine/lib/antlr3/antlr3/recognizers.py
adding ../../../../google_appengine/lib/antlr3/antlr3/streams.py
adding ../../../../google_appengine/lib/antlr3/antlr3/tokens.py
adding ../../../../google_appengine/lib/antlr3/antlr3/tree.py
adding ../../../../google_appengine/lib/antlr3/antlr3/treewizard.py
adding ../../../../google_appengine/lib/antlr3/antlr_python_runtime.egg-info/PKG-INFO
adding ../../../../google_appengine/lib/antlr3/antlr_python_runtime.egg-info/SOURCES.txt
adding ../../../../google_appengine/lib/antlr3/antlr_python_runtime.egg-info/dependency_links.txt
adding ../../../../google_appengine/lib/antlr3/antlr_python_runtime.egg-info/top_level.txt
adding ../../../../google_appengine/lib/antlr3/setup.py
adding ../../../../google_appengine/lib/cacerts/cacerts.txt
adding ../../../../google_appengine/lib/cacerts/urlfetch_cacerts.txt
adding ../../../../google_appengine/lib/fancy_urllib/__init__.py
adding ../../../../google_appengine/lib/fancy_urllib/fancy_urllib/__init__.py
adding ../../../../google_appengine/lib/ipaddr/ipaddr/COPYING
adding ../../../../google_appengine/lib/ipaddr/ipaddr/README
adding ../../../../google_appengine/lib/ipaddr/ipaddr/__init__.py
adding ../../../../google_appengine/lib/ipaddr/ipaddr/ipaddr_test.py
adding ../../../../google_appengine/lib/ipaddr/ipaddr/setup.py
adding ../../../../google_appengine/lib/yaml/LICENSE
adding ../../../../google_appengine/lib/yaml/PKG-INFO
adding ../../../../google_appengine/lib/yaml/README
adding ../../../../google_appengine/lib/yaml/examples/yaml-highlight/yaml_hl.cfg
adding ../../../../google_appengine/lib/yaml/examples/yaml-highlight/yaml_hl.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/__init__.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/composer.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/constructor.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/cyaml.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/dumper.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/emitter.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/error.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/events.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/loader.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/nodes.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/parser.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/reader.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/representer.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/resolver.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/scanner.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/serializer.py
adding ../../../../google_appengine/lib/yaml/lib/yaml/tokens.py
adding ../../../../google_appengine/lib/yaml/setup.cfg
adding ../../../../google_appengine/lib/yaml/setup.py
adding ../../../../google_appengine/lib/yaml/setup_with_libyaml.py
adding ../../../../google_appengine/templates/logging_console.js
adding ../../../../google_appengine/templates/logging_console_footer.html
adding ../../../../google_appengine/templates/logging_console_header.html
adding ../../../../google_appengine/templates/logging_console_middle.html
adding ../../../../nersc.test
adding ../../../../pricing2.pickle
adding ../../../../test.py
adding ../../../../version.py
"""
import os
for line in a.split('\n'):
    if line.strip():
        os.system('hg forget %s' % (line[7:].strip()))
